services:
  uptime-monitor:
    build: .
    container_name: simple-uptime-monitor
    restart: always
    ports:
      - "5080:5090"
    environment:
      - NODE_ENV=production
      - PORT=5090
    volumes:
      - ./public:/app/public:ro
      - ./server.js:/app/server.js:ro
      - ./data:/app/data
    networks:
      - cloudflare-tunnel-vps

networks:
  cloudflare-tunnel-vps:
    external: true
